name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This is your first issue. Please remain patient, your issue will be seen to shortly'
        pr-message: 'Thanks for contributing to the Boxer project.'
